Repository unb-mds/LicitaBSB-24.1, pull requests merged in 2024-08, with the labels that each got.

#117 116 atualização do documento de arquitetura
  backend/extrair_dados_csv/README.md
  backend/extrair_dados_csv/dados_csv.json
  docs/Arquitetura/Diagrama_vai.png
  docs/Arquitetura/arquitetura.md
  docs/Arquitetura/diagrama_final.png
Labels: Documentação

#133 Landing page bidding
  frontend/src/components/card-licitacoes/index.jsx
  frontend/src/components/card-licitacoes/style.module.css
  frontend/src/main.jsx
  frontend/src/pages/bidding-search-list/index.jsx
  frontend/src/pages/bidding-search-list/style.module.css
  frontend/src/pages/landing/ultimas-licitacoes/index.jsx
  frontend/src/pages/landing/ultimas-licitacoes/style.module.css
  frontend/src/services/licitacoes.service.js
Labels: bug, Feature

#137 Refactor bidding page
  frontend/src/components/card-licitacoes/index.jsx
  frontend/src/components/card-licitacoes/style.module.css
  frontend/src/pages/bidding-list/filter/index.jsx
  frontend/src/pages/bidding-list/index.jsx
  frontend/src/pages/bidding-page/index.jsx
  frontend/src/pages/bidding-page/style.module.css
  frontend/src/pages/landing/index.jsx
  frontend/src/pages/landing/ultimas-licitacoes/style.module.css
  frontend/src/services/licitacoes.service.js
  frontend/src/styles/global.css
Labels: bug, Feature

#138 Corrigir importação de imagens das páginas dos artigos.
  frontend/src/pages/about-bidding-dispatch/index.jsx
  frontend/src/pages/about-bidding/index.jsx
  frontend/src/pages/about-bot/index.jsx
Labels: bug

#143 Implementação do Dashboard
  frontend/src/pages/dashboard/index.jsx
  frontend/src/pages/dashboard/style.module.css
Labels: Feature

#152 Adicionando a sidebar do celular
  frontend/assets/burger.svg
  frontend/src/components/footer/index.jsx
  frontend/src/components/footer/style.module.css
  frontend/src/components/header/index.jsx
  frontend/src/components/header/style.module.css
  frontend/src/components/sidebar-responsive/index.jsx
  frontend/src/components/sidebar-responsive/style.module.css
  frontend/src/main.jsx
  frontend/src/pages/about-licitaBSB/style.module.css
Labels: Feature

#154 Feat implementando funcionalidades filter
  frontend/src/components/header/__snapshots__/header.test.js.snap
  frontend/src/components/header/header.test.js
  frontend/src/components/layout/custom-input-checkbox/index.jsx
  frontend/src/components/newsletter/style.module.css
  frontend/src/pages/about-bot/__snapshots__/about-bot.test.js.snap
  frontend/src/pages/about-licitaBSB/__snapshots__/about-lisitaBSB.test.js.snap
  frontend/src/pages/bidding-list/filter/index.jsx
  frontend/src/pages/bidding-list/index.jsx
  frontend/src/pages/landing/ultimas-licitacoes/index.jsx
Labels: bug, Feature

#157 Feat implementando carrossel de artigos na home page
  frontend/assets/carrossel/1.png
  frontend/assets/carrossel/2.png
  frontend/assets/carrossel/3.png
  frontend/assets/carrossel/4.png
  frontend/src/mocks/carrossel.js
  frontend/src/pages/landing/carrossel/index.jsx
  frontend/src/pages/landing/carrossel/style.module.css
  frontend/src/pages/landing/index.jsx
Labels: Feature

#158 Feat implementando funcionalidades de busca por palavra chave na header
  frontend/src/components/header/index.jsx
  frontend/src/pages/landing/carrossel/index.jsx
Labels: bug

#162 test: Atualizando testes unitários
  frontend/assets/download.jpg
  frontend/src/components/footer/__snapshots__/footer.test.js.snap
  frontend/src/components/footer/footer.test.js
  frontend/src/components/header/header.test.js
  frontend/src/pages/about-us/card-member/card-member.test.js
  frontend/src/pages/about-us/card-member/index.jsx
  frontend/src/pages/about-us/card-member/style.module.css
  frontend/src/pages/about-us/index.jsx
  frontend/src/pages/about-us/style.module.css
Labels: Feature, Test

#163 Readme
  README.md
  frontend/README.md
  frontend/assets/README.md
  frontend/coverage/README.md
  frontend/public/README.md
  frontend/src/README.md
Labels: Documentação
